events {}

http {
    upstream backend {
    server app1:80 max_fails=3 fail_timeout=10s;
    server app2:80 max_fails=3 fail_timeout=10s;
    server app3:80 max_fails=3 fail_timeout=10s;
}

    server {
        listen 80;

        location / {
            proxy_pass http://backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
